apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - deployment-payload-cms.yaml
  - service-payload-cms.yaml
  - ingress.yaml

commonLabels:
  owner: edwardnafornita
namespace: default
